### PR TITLE
Built Map 

### PR DESCRIPTION
**Pull request by connor-bennett**
Created Interactive map with leaflet (Nearly done)

### CODE REVIEW

**Review by BhavikChand — CHANGES_REQUESTED** [review]
package.json should have no mysql repeated.

**Review by connor-bennett — COMMENTED** [review]
great

**Review by BhavikChand — APPROVED** [review]
lgtm

**Review by BhavikChand — APPROVED** [review]
lgtm

**Comment by connor-bennett** [comment]
merged map

**Pull request merged**
